### PR TITLE
LPS-61501 show public/private pages as tabs

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, this makes the public/private pages to work as links. let me know if I can help you, 
thanks!!

(This one also includes https://github.com/evannagayama/liferay-portal/pull/365 so you can choose if you want to go with the other one first or all together)

hija_de_hija_-_liferay

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hey @marcoscv-work, @natecavanaugh, @pat270

I have added some css both to the theme and the portlet to make the tree look more similar to the mockups. Could you please review those changes? thanks!

The js changes have already been reviewed by @jbalsas

**Comment by pat270** [comment]
Hey @juliocamarero, I don't see any problems with these changes.

**Comment by evannagayama** [comment]
@anthony-chu can you take a look at these and make test fixes? Thanks!

**Comment by anthony-chu** [comment]
@juliocamarero 

It appears that a user cannot add a sibling public page (not a child page). Clicking the + icon next to Public Pages does not add it, nor does clicking the cog icon next to Public Pages, then the + icon. I've documented this issue in the GIF below:
cannot-add-public-pages

**Comment by juliocamarero** [comment]
Hey @anthony-chu  I just added another commit fixing this. Could you please test again?

thanks a lot!!! :)

**Comment by anthony-chu** [comment]
New pull request submitted here: #371.

**Pull request closed without merging**
