### PR TITLE
LPS-62586 Sets redirect to structures

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by vicnate5** [comment]
@evannagayama In this pull, wc structures are no longer managed in an iframe

**Comment by evannagayama** [comment]
@brianwulbern  can you take a look at this and make test fixes? Thanks!

**Comment by ealonso** [comment]
Hey guys,

You can check some comments and screenshots on the previous pull: https://github.com/evannagayama/liferay-portal/pull/451

Regards,
Eudaldo.

**Comment by brianwulbern** [comment]
Thanks @ealonso!

@evannagayama 
Looking into the fix now...

**Comment by brianwulbern** [comment]
@ealonso @evannagayama 

See the pull here: https://github.com/evannagayama/liferay-portal/pull/464

**Pull request closed without merging**
