### PR TITLE
master-qa-16424

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-16424

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed back to KGai.
In the future commit the big change by itself and all the little changes in a separate pull request or separate tickets.

For this commit: https://github.com/koor4356/liferay-portal/commit/54e6981ab1d4ddbf9ae5c1d0ed381446641a8b2e

1. Move the "addPage" command into a PageNavigator.macro and name it something like "gotoAddPage"
2. Change this macro command "addPageButton" to "saveAddPage"
3. In "addPageToSiteTemplates" 
	1. Remove the Page#gotoCP and call it all the testcase level
	2. Make the SiteTemplates#manageSiteTemplates a SiteTemplatesNavigator#gotoManageSiteTemplate
	3. Remove the last 2 macro commands and put them into another macro, SiteTemplatesNavigator#gotoSiteTemplatePage  SiteTemplates#viewSiteTemplatePage
	4. The finished result could look something like this:
```
	Page.macro
	<command name="addPageToSiteTemplates">
		<execute macro="SiteTemplatesNavigator#gotoManageSiteTemplates" />

		<execute macro="PageNavigator#gotoAddPage" />

		<execute macro="Page#saveAddPage" />
	</command>

	SiteTemplates.macro
	<command name="viewSiteTemplatePage">
		<execute macro="SitePageNavigator#gotoSiteTemplatePage">
			<var name="pageName" value="${pageName}" />
			<var name="siteTemplateName" value="${siteTemplateName}" />
		</execute>

		<execute macro="Navigator#_gotoPage">
			<var name="pageName" value="${pageName}" />
		</execute>
	</command>
```
4. After you make all the macro changes make sure to edit the tests that will be affected.
5. Make sure to explicitly declare the variables in each macro, because in poshi runner they won't be automatically passed in.

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF for KGai.
1. SiteTemplates.macro delete viewSiteTemplatePage and put the Navigator_gotoPage into gotoSiteTemplatesPage
2. Extract typing into title, out of PageNavigator#gotoAddPage and put into a Page#addPageTitle macro command

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/471

**Pull request closed without merging**
