### PR TITLE
master-lps-57562

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-57562

### CODE REVIEW

**Comment by anthony-chu** [comment]
This is a resend of brianchandotcom#32308 with front-end fixes on top.

/cc @juliocamarero I included an auto-SF that the source-formatter caught. Can you take a look and see if the SF breaks anything functionally? Thanks!

**Comment by juliocamarero** [comment]
that looks great, thanks @anthony-chu! this was probably an issue while rebasing.

**Comment by jkappler** [comment]
Hi @anthony-chu, seems that there was a problem with the rebase and that variable was added to the class. But it is not used at all. That's why the SF is failing and now it's giving this compilation error. Do you want to close the issue and we will resend tomorrow? Or in the SF, just remove the variable and send to Brian?

Thanks for the time

cc: @juliocamarero

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@jkappler I removed the variable in the SF commit. Can you or @juliocamarero take a look to make sure things are right? Thanks!

**Comment by evannagayama** [comment]
New PR here: https://github.com/brianchandotcom/liferay-portal/pull/32396

**Pull request closed without merging**
