### PR TITLE
LPS-61501 Async load of product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by anthony-chu** [comment]
@juliocamarero It looks like there are rebase errors for this pull request. Could you take a look into them? Thanks!

**Comment by juliocamarero** [comment]
@anthony-chu done!

**Comment by juliocamarero** [comment]
ci:retes

**Comment by anthony-chu** [comment]
Thanks @juliocamarero! New pull request here: #392.

**Pull request closed without merging**
