### PR TITLE
master-qa-20706

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-20706

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@anthony-chu can you rebase this? Thanks

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34004

**Pull request closed without merging**
