### PR TITLE
LPS-61582 Pages panel should remember the state

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @evannagayama 

this pull makes the "Pages" panel to remember if you leave it closed or open. (Previously it was open by default).

This fails some tests that expect the panel to be open. 

thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by evannagayama** [comment]
Thanks Julio, I'll take a look and make test fixes.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@brianwulbern can you look into this and make test fixes? Thanks!

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
pr here: https://github.com/evannagayama/liferay-portal/pull/406

**Pull request closed without merging**
