### PR TITLE
master-qa-16350

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-16350

### CODE REVIEW

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF for KGai.
Next time I think you could split up the commits a little more, but for now it's pretty simple so I think it's ok.

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/447

**Pull request closed without merging**
