### PR TITLE
LPS-61533 async product menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@juliocamarero It appears there is a js error preventing the success message from displaying when publishing a blogs entry. Can you take a look into it? Thanks!

**Comment by juliocamarero** [comment]
Awesome! there was a ; missing

thanks a lot!!

https://github.com/brianchandotcom/liferay-portal/pull/34441

**Pull request closed without merging**
