### PR TITLE
master-lps-62065

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LPS-62065

### CODE REVIEW

**Comment by evannagayama** [comment]
re https://github.com/evannagayama/liferay-portal/pull/458

**Comment by koor4356** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @evannagayama, 

I've fixed  the SourceFormatter error here: https://github.com/evannagayama/liferay-portal/pull/473

**Pull request closed without merging**
