### PR TITLE
LPS-60646 Don't show the management bar and search input if we don't have results for select

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

This pull brokes many poshi test, Could you take a look?

The changes on the views are:
* I've removed the summary tab
* Now the assign roles view and the select users, organizations and user groups views are open using a pop-up. 
* The default view is "icon"
* The searchContainer ID were changed

Let me know if you have any question.

Thanks!!!

**Comment by evannagayama** [comment]
@ealonso & @anthony-chu 

This one has already been closed: https://github.com/brianchandotcom/liferay-portal/pull/32461. Did you mean to commit these on the same ticket? Thanks

**Comment by ealonso** [comment]
Yes, is the same changes, I've sent some parts before, to make the review for Brian easier, because the pull had more than 50 commits.

**Comment by ealonso** [comment]
@evannagayama @anthony-chu

**Comment by evannagayama** [comment]
Thanks Eudaldo, anthony will be working on the tests fixes.

**Comment by anthony-chu** [comment]
@ealonso 

I tried to add a site member to a site team, but clicking "Add" after selecting the site member does not add the user to the site team. I've attached a gif to better describe what I am seeing:

lps-60646-site-team-cannot-assign

**Comment by ealonso** [comment]
Hey @anthony-chu,

I've resent the pull with the fix, please see https://github.com/evannagayama/liferay-portal/pull/260

Thanks!!!

**Pull request closed without merging**
