### PR TITLE
LPS-60985 apply qa-id pattern

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hi Evan, 

I have added some more qa-ids as you requested. Can you please let me know if you miss another one?

thank you!


web_content_-_liferay

**Comment by juliocamarero** [comment]
ci:retest

**Comment by evannagayama** [comment]
@juliocamarero I'll work on this one. Thanks!

**Comment by evannagayama** [comment]
there's a source-format issue on master. After that's fixed I'll push this in https://github.com/evannagayama/liferay-portal/tree/master-en-298

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33137

**Pull request closed without merging**
