### PR TITLE
master-qa-23865

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-23865

### CODE REVIEW

**Comment by anthony-chu** [comment]
Just as a heads up, this pull request might die the first time around, since the PR tester will go down at noon.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38365

**Pull request closed without merging**
