### PR TITLE
master-qa-22807

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-22217
https://issues.liferay.com/browse/LRQA-22689
https://issues.liferay.com/browse/LRQA-22773
https://issues.liferay.com/browse/LRQA-22807

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama @sharonchoi

We're seeing success message failures on CPDocumentsandmedia#MoveToRecycleBinDocument, so I swapped the assertion order to be: 1) no DM items in portlet; 2) success message

Hopefully that will limit/remove the flakiness.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by sharonchoi** [comment]
@brianwulbern test needs to be turned off due to bug, @brianchiu will be doing so, soon. 
Bug: https://issues.liferay.com/browse/LPS-63904

**Comment by evannagayama** [comment]
Good fixes, and thanks for finding the wildfly issue.

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37132

**Pull request closed without merging**
