### PR TITLE
LPS-61501 Async load of product menu

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, 

this pull makes that the first time you open the product menu, it will be loaded using ajax. Therefore, users may see a "loading" gif before the product menu appears. Some tests are failing for this reason, they try to interact with the product menu before it is fully loaded.

Thanks a lot!!

### CODE REVIEW

**Comment by evannagayama** [comment]
@anthony-chu can you take a look at this and make any necessary test fixes? Thanks!

**Comment by anthony-chu** [comment]
@juliocamarero

I finished building the branch, and it appears that the product menu toggle icon in the control menu is not visible.
product-menu-toggle-not-visible

The markup shows a hidden element, but selenium ide is able to locate and interact with the element. Could you take a look into it? Thanks!

**Comment by juliocamarero** [comment]
Hey @anthony-chu 

I just reproduced that one and fixed it in my last commit. I still can not reproduce the one from the screenshots. Let me know if you can reproduce that one.

thanks a lot!

**Comment by juliocamarero** [comment]
Hey @anthony-chu 

I just reproduced the other issue. Working on a fix...

**Comment by juliocamarero** [comment]
Ok, I think I found it. New pull here: https://github.com/evannagayama/liferay-portal/pull/390

please let me know if you still find any issue there. Thanks a lot!!

**Pull request closed without merging**
