### PR TITLE
LRQA-19777- TestCase Complete for SiteMap TestPlan with Public Pgs & Children Pgs

### PR DESCRIPTION
**Pull request by asungutierrez**

### CODE REVIEW

**Comment by evannagayama** [comment]
Hi Asun,

Please make these changes to your pull request. Please let me know if you have any questions or issues you run into. Thank you

<h6>OVERALL:</h6>

1. After reverting all the changes below to their original state you will have to update all the variables back to what they were.
2. Unify commit messages. Some have "LPS-19777:" or "LPS-19777-". They should all be "LRQA-19777"
 * This commit message "AssertTextEquals.function file with modified argument" needs to have the ticket before it

<h6>SPECIFIC CHANGES:</h6>
1. LPS-19777: Test Case for SiteMap for Public Page and Child Page
 a. In `portal-web/test/functional/com/liferay/portalweb/macros/Portlet.macro` - Change the variable back to ${portletName}

2. LPS-19777: Sites are deleted in "tear-down" tag
 a. Remove this commit

3. LRQA-19777 Site Map test plan
 a. In `portal-web/test/functional/com/liferay/portalweb/macros/Page.macro` - Revert this to the previous variables
 b. `portal-web/test/functional/com/liferay/portalweb/paths/pathlib/uisections/NavBar.path` Use this symbol " | " because some of the search fields may not contain the data-qa-id. Example below:
`//*[@data-qa-id='searchInput'] | //div[contains(@class,'navbar-
default')]//input[contains(@id,'keywords')]`

4. LRQA-19777 Variable Site is empty before site map portlet
 a. In `portal-web/test/functional/com/liferay/portalweb/macros/ProductMenuHelper.macro` - Revert this back to what it was before

**Comment by evannagayama** [comment]
Closing for the above fixes. Please push again when ready.

**Comment by evannagayama** [comment]
ci:retest

**Comment by asungutierrez** [comment]
ci:retest

**Comment by evannagayama** [comment]
@asungutierrez I think you forgot one part.

> LRQA-19777 Variable Site is empty before site map portlet
a. In portal-web/test/functional/com/liferay/portalweb/macros/ProductMenuHelper.macro - Revert this back to what it was before

Could you revert the changes in ProductMenu.macro & ProdcutMenuHelper.macro from the commit: `LRQA-19777 Variable Site is empty before site map portlet`

**Comment by evannagayama** [comment]
Hey @asungutierrez,

You can fetch my branch with the revert here: https://github.com/evannagayama/liferay-portal/tree/master-en-589. I made a new commit to revert the things I noted before. 

Could you do one more thing and run "ant format-source" until it's done formatting all the changes. You can run it at the location ~/private/liferay-portal-master/portal-impl$. Ant format-source formats the line spacing and checks for common mistakes.

**Pull request closed without merging**
