### PR TITLE
master-qa-15900

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-15900

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by kmaria** [comment]
ci:retest

**Comment by evannagayama** [comment]
@kmaria, 

I think the change you made will only fix the tests with an export/import template. Could you check and fix the navigation for all the export and import cases? 
For example in this one: <execute macro="LAR#gotoExportSite" />
And also before or in this one: <execute macro="LAR#importSiteCP">

**Comment by kmaria** [comment]
only LAR#gotoImportSiteCmd contained gotoPagesCP, that is modified according to changes.
LAR#importSiteCP calls LAR#gotoImportSiteCmd
LAR#gotoExportSiteCmd and LAR#gotoExportSite are basically identical for a reason

**Comment by evannagayama** [comment]
@kmaria,
Sorry here's a clarification:

I agree that the macros are ok, but I think where they are called (mainly in the testcase level) the navigation needs to be changed. For example if you look at ExportImport#ExportImportSmoke it will fail, because it still navigates to the Site Pages.

There are more instances of this issue in many different tests and this navigation will cause them to fail. Could you please search for all these instances (export and import) and change the navigation?

Let me know if you have questions or don't understand what I'm saying. I think it's easier to see it and I can skype if needed. Thanks Maria!

**Pull request closed without merging**
