### PR TITLE
LPS-63667 Fix functional tests

### PR DESCRIPTION
**Pull request by jkappler**
Hi @evannagayama, we renamed another category. This time we renamed Pages for Navigation. I tried to fix the tests just like I did when renaming Users, but I keep getting 1 error. I really don't know if it's related. Please let me know if the changes are correct :D

Again, thanks for the time!

CC:// @juliocamarero

### CODE REVIEW

**Comment by evannagayama** [comment]
@anthony-chu or @brianwulbern, can you look into this and make test fixes? Thanks!

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
Conflicts solved and branch updated

**Comment by jkappler** [comment]
ci:retest

**Comment by jkappler** [comment]
@anthony-chu, @brianwulbern, seems all test pass!!!!!

Could you please review the changes I made to the functional tests? Thanks!!!!

cc:/ @juliocamarero

**Comment by jkappler** [comment]
Will send directly to Brian, will cc you guys on that one

**Comment by brianwulbern** [comment]
Nice!

**Pull request closed without merging**
