### PR TITLE
LPS-62077 Sets the portlet description with the entries max age time description

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

Could you take a look at poshi errors?

I've moved the empty recycle bin button from here:
recycle_bin_-_liferay
to:
recycle_bin_-_liferay

Also, I've moved the info message to portlet title icon help.

**Comment by evannagayama** [comment]
@ealonso thanks we'll take a look. @koor4356 can you take a look and make test fixes. Thanks!

**Comment by koor4356** [comment]
Thanks @ealonso, 
I will look into this poshi error.

**Comment by koor4356** [comment]
Hi @ealonso, Poshi Fixes has been pushed to @evannagayama here https://github.com/evannagayama/liferay-portal/pull/400

**Pull request closed without merging**
