### PR TITLE
master-qa-14739

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-14739

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25313

**Comment by brianchiu** [comment]
@brianwulbern @evannagayama 

You can close this pull.

**Comment by brianwulbern** [comment]
@brianchiu Thanks!  Closing.

**Pull request closed without merging**
