### PR TITLE
master-qa-22472

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-22472

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
These two tests are known failures, listed here: brianchandotcom#36626.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36930

**Pull request closed without merging**
