### PR TITLE
LPS-61176 Fix test

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @evannagayama,

Let me know if you need help with something. I think, the only real test failure is PoshiRunner.test[SitelocalizationUsecase#SiteTemplateLocalization].

Thanks!!!

**Comment by evannagayama** [comment]
Yeah, thanks @ealonso there's been a lot of random issues. I'll try to get it done today.

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33702

**Pull request closed without merging**
