### PR TITLE
LPS-614645 not needed div

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @evannagayama this part of the product menu is very fragile because I just removed a div and it started failing. I can add the qa-ids that you need to make this more robust. how do would you feel about this proposal? I can add those on Monday. Can you add to this picture the elements you use? I can add qa-id to all of them.

welcome_-_liferay


thanks a lot!

**Comment by evannagayama** [comment]
controlmenu

**Comment by evannagayama** [comment]
Hi Julio, I think those are good. We have a few more that we suggest in the screenshot and details below:

1. cogIcon - applied to all in portal
2. ellipsisIcon - applied to all in portal
3. groupHeadingPanel - applied to the header dropdown panels in the control menu. Maybe there is a better name for this?
4. panelMenuItem - applied the next level of menu items. If these are the same as the menu items in the ellipsis, maybe we can have them applied there too with a generic name: menuItem?

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33682

**Pull request closed without merging**
