### PR TITLE
master-qa-16609

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-16609

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Hey BWul,

Can you rebase this branch, there was a conflict issue with LPS-56767. I think you could also remove the ticket LPS-56767.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/490

**Pull request closed without merging**
