### PR TITLE
LPS-61140 Keep open error alerts

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hi Evan! Could you please take a look on poshi erros? Thanks!

**Comment by brianwulbern** [comment]
@carloslancha @evannagayama 

I'm looking into the errors now :)

**Comment by brianwulbern** [comment]
@carloslancha @evannagayama 

See the pull with the fix here: https://github.com/evannagayama/liferay-portal/pull/407

**Comment by carloslancha** [comment]
Thanks @brianwulbern !

**Pull request closed without merging**
