### PR TITLE
LPS-64013 - Admin theme needs atlas variables

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama:

We've changed the type selection when we are adding a new page from a radio button selectors:

captura_de_pantalla_10_3_16_10_55
 
to drop down menu selection:

https___test-1-11_liferay_com_usercontent_jobs_test-portal-acceptance-pullrequest_master__builds_1092_test-portal-acceptance-pullrequest-batch_master__axis_variable_7_label_exp__master_functional-tomcat8-mysql56-jdk7_1_cppagetemplates_23add

Could you please take a look at poshi errors?

Thanks!!!

**Comment by ealonso** [comment]
cc\

@natecavanaugh, @marcoscv-work

**Comment by evannagayama** [comment]
@ealonso @juliocamarero

Will this pr need to be backported to 7.0.x??

**Comment by ealonso** [comment]
Yes, we would like it to be backported to 7.0.x

**Comment by evannagayama** [comment]
@ealonso sorry can you rebase this? I'll try to work on this today. Thanks!

**Comment by ealonso** [comment]
@evannagayama resend here: https://github.com/evannagayama/liferay-portal/pull/633

**Pull request closed without merging**
