### PR TITLE
master-lps-61582

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21152

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
These tests are failing in all pulls, I think we are good! :+1: 

thanks a lot!! https://github.com/brianchandotcom/liferay-portal/pull/34809

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34809

**Pull request closed without merging**
