### PR TITLE
LPS-60965 Adds markupView lexicon to edit_article

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

Could you please take a look at the poshi error?

Thanks!!!

**Comment by ealonso** [comment]
HTML Before changes:

```
<span class="taglib-workflow-status">
	<span class="workflow-id">
		<span class="workflow-label">ID:</span>
		<span class="workflow-value">20847</span>
	</span>
	<span class="workflow-version">
		<span class="workflow-label">Version:</span>
		<strong class="workflow-value">1.0</strong>
	</span>
	<span class="workflow-status">
		<strong class="label status workflow-status-approved approved workflow-value"> Approved </strong>
	</span>
	<span class="taglib-icon-help">
		<img alt="" aria-labelledby="gefi" onblur="Liferay.Portal.ToolTip.hide();" onfocus="Liferay.Portal.ToolTip.show(this);" onmouseover="Liferay.Portal.ToolTip.show(this);" src="http://master.liferay.org.es/o/frontend-theme-admin-web/admin/images/portlet/help.png" tabindex="0">
		<span class="hide-accessible tooltip-text" id="gefi">A new version is created automatically if this content is modified.</span>
	</span>
</span>
````

HTML After changes:

```
<span class="taglib-workflow-status">
	<span class="workflow-id">
		<span class="workflow-label">ID:</span>
		<span class="workflow-value">21638</span>
	</span>
	<span class="workflow-version">
		<span class="workflow-label">Version:</span>
		<span class="workflow-value">1.0</span>
	</span>
	<span class="workflow-status">
		<span class="status workflow-status-approved approved workflow-value"> Approved </span>
	</span>
	<span class="taglib-icon-help">
		<img alt="" aria-labelledby="fqcx" onblur="Liferay.Portal.ToolTip.hide();" onfocus="Liferay.Portal.ToolTip.show(this);" onmouseover="Liferay.Portal.ToolTip.show(this);" src="http://localhost:8080/o/frontend-theme-admin-web/admin/images/portlet/help.png" tabindex="0">
		<span class="hide-accessible tooltip-text" id="fqcx">A new version is created automatically if this content is modified.</span>
	</span> 
</span>
```

**Comment by ealonso** [comment]
The main difference is we changed the strong tag for a span tag

**Comment by ealonso** [comment]
You can check the poshi errors here https://github.com/brianchandotcom/liferay-portal/pull/32917 before it finish

**Comment by evannagayama** [comment]
Pushed to EAlonso.
https://github.com/ealonso/liferay-portal/pull/570

**Pull request closed without merging**
