### PR TITLE
master-lps-60991

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-60991

### CODE REVIEW

**Comment by anthony-chu** [comment]
This is a resend of #292 with frontend test fix to add tags in the metadata panel.

**Comment by ealonso** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF For AChu.
Applied the paths to other macro commands.

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32965

**Pull request closed without merging**
