### PR TITLE
master-lps-62012

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21421

### CODE REVIEW

**Comment by evannagayama** [comment]
re:https://github.com/evannagayama/liferay-portal/pull/420

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
ref: https://github.com/evannagayama/liferay-portal/pull/420

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama 

All good :)

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35064

**Pull request closed without merging**
