### PR TITLE
pr-3773-me

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LPS-57564

### CODE REVIEW

**Comment by koor4356** [comment]
@juliocamarero, @evannagayama ,I just sent to pr to Evan. 
https://github.com/evannagayama/liferay-portal/pull/248

**Comment by evannagayama** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
replaced by this one https://github.com/evannagayama/liferay-portal/pull/253

**Pull request closed without merging**
