### PR TITLE
master-qa-25157

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-25157
https://issues.liferay.com/browse/LRQA-25674

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama 

I triggered both of these tests (CPWebcontent#AddWebContentWithImageField & WebcontentpublicationUsecase#AddAndEditAssetsViaVirtualHostOrganizations) to run on CI here: https://github.com/brianwulbern/liferay-portal/pull/144

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Nice fixes. Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/40558

**Comment by brianwulbern** [comment]
resent in: https://github.com/evannagayama/liferay-portal/pull/759

**Pull request closed without merging**
