### PR TITLE
master-qa-20490

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-20490
https://issues.liferay.com/browse/LRQA-20531

### CODE REVIEW

**Comment by anthony-chu** [comment]
cc @sharonchoi austinchiang

I've made BlogsEditEntry#SETTINGS_SECTION applicable for both the Blogs admin and page portlets.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF For AChu.
1. Changed the tear down site to Liferay, because the site Site Name will be deleted anyway
2. Updated path to make a little more robust

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33735

**Pull request closed without merging**
