### PR TITLE
master-lps-60244

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LPS-60244

### CODE REVIEW

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF For KGai.
1. Next time you can combine those commits because they are the same logically
2. Removed the function typeAlloyEditor

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36260

**Pull request closed without merging**
