### PR TITLE
master-qa-21778

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-21778
https://issues.liferay.com/browse/LRQA-21738

### CODE REVIEW

**Comment by anthony-chu** [comment]
@vicnate5
- 011ca58 adds the new locator specifically for the name link
- 4e844f6 I checked through all the uses of these locators, and they are all assertions. I've gone ahead and checked the table locators instead of the link. Let me know if this is an approach that can be taken. If not, I can remove just this commit.

**Comment by vicnate5** [comment]
Looks like it should be fine. Thanks.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
@anthony-chu next time can you try to merge some of the commits so it's not as huge? Thanks!

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35655

**Pull request closed without merging**
