### PR TITLE
master-qa-19013

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-19013

### CODE REVIEW

**Comment by evannagayama** [comment]
@anthony-chu & @brianwulbern,

Later we should clean up this test and macro functions.
1. Putting all the functions into macros
2. Probably adding a macro to change permissions for structures and templates
3. Separating out saving and adding permissions in this WebContentStructures#saveCP

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32018

**Comment by brianwulbern** [comment]
@anthony-chu @evannagayama 

Have just the ticket for that: https://issues.liferay.com/browse/LRQA-15879

**Comment by evannagayama** [comment]
awesome, thanks!

**Pull request closed without merging**
