### PR TITLE
LPS-62065 Replace add content panel and simulator panel for lexicon panels

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

We've replace the old panels (add panel and simulator panel) for the new lexicon panels, like product menu.

Let me know if I can help you with anything.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
ci:retest

**Comment by evannagayama** [comment]
@ealonso I ran into some rebase issues when updating. Can you rebase and resend? Thanks!

**Comment by ealonso** [comment]
Resend: https://github.com/evannagayama/liferay-portal/pull/445

**Pull request closed without merging**
