### PR TITLE
LPS-61140 - Implement new alert component in error taglib

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by brianwulbern** [comment]
Like Julio noted [here](https://github.com/evannagayama/liferay-portal/pull/423), these tests are failing across all the PRs now.  So it looks good!

**Comment by evannagayama** [comment]
re: https://github.com/evannagayama/liferay-portal/pull/407

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34822

**Comment by evannagayama** [comment]
Thanks @carloslancha & @brianwulbern

**Pull request closed without merging**
