### PR TITLE
master-qa-13393

### PR DESCRIPTION
**Pull request by kmaria**
https://issues.liferay.com/browse/LRQA-13393

### CODE REVIEW

**Comment by kmaria** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ref: https://github.com/evannagayama/liferay-portal/pull/121

**Comment by evannagayama** [comment]
SF for Maria.
Moved the variables into the test

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/388

**Pull request closed without merging**
