### PR TITLE
master-qa-23992

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-23992
https://issues.liferay.com/browse/LRQA-24294
https://issues.liferay.com/browse/LRQA-24345

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:stop

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianwulbern** [comment]
@evannagayama Looks like that won't work, looking at alternatives...

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
See https://github.com/evannagayama/liferay-portal/pull/705

**Pull request closed without merging**
