### PR TITLE
master-lps-61071

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-61071

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama, @anthony-chu, @koor4356

The test failures was causes by LPS-61128, I applied some lexicon patterns to configuration portlet, I didn't know why Brian merge it. Could you please take care on the poshi erros?

Thanks you very much!!!

**Comment by ealonso** [comment]
- I've change the tabs for a navigation bar
 - I added the dialog-footer class to boton row div.

Please let me know if you need some help.

**Comment by anthony-chu** [comment]
hi @ealonso 
some of the failures at head were resolved by brianchandotcom#33138. retesting to see what failures remain after victor's fix.
ci:retest

**Comment by anthony-chu** [comment]
it looks like the remaining failures are known issues.

**Comment by ealonso** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33246

**Pull request closed without merging**
