### PR TITLE
LRQA-19777 SiteMap Portlet Privates Pages

### PR DESCRIPTION
**Pull request by asungutierrez**

### CODE REVIEW

**Comment by evannagayama** [comment]
ref https://github.com/evannagayama/liferay-portal/pull/607

**Comment by asungutierrez** [comment]
ci:retest

**Comment by evannagayama** [comment]
Nice job, first test committed! I made some changes and comments below. Please let me know if you have any questions.

SF for @asungutierrez

Please link the lrqa ticket in the commit message when you submit a pr 

Update paths - 96eceb736125991b2f5e97d1192e641cdeed868a
1. Changed path file name SiteMapConf to SiteMapConfiguration
2. Removed comment ""
3. Removed CONF_WINDOW_TITLE because it exists as Iframe#IFRAME_TITLE
4. Removed SAVE_BUTTON because it exists as Button#SAVE

Updated test - 6722acb2873526825da937d1efee69458beef318
1. Renamed test DisplayPrivatePagesWChildrenPagesasAdms to DisplayPrivatePageWithChildPage because it's only displaying one page and we usually assume the test user is Admin. We only need to specify the user permission if it's something other than admin.
2. I made this a priority 4 because I don't think it's a critical test.
2. The setup only makes a private page and a child page on the private page. I know you have other tests that have public pages, so in the future this will need to be updated.

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37350

**Pull request closed without merging**
