### PR TITLE
LPS-61545 Uses sidebar-header for title

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama ,

Could you please take a look at poshi errors?

Before:

welcome_-_liferay

After:

welcome_-_liferay

I've replaced the tabs for an accordion.

Thanks!!!

**Comment by evannagayama** [comment]
@anthony-chu, can you take a look at this and make test fixes? Thanks!

**Comment by ealonso** [comment]
@anthony-chu, I've just updated the pull

**Comment by anthony-chu** [comment]
@ealonso thanks! i'll take a look at the updated pull

**Pull request closed without merging**
