### PR TITLE
LPS-63004 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jkappler** [comment]
Hi @evannagayama, we made some changes to some navigations in Site Admin, and that's why the tests are failing.

Some changes that where made:

- Column with site name has a link to child sites view if it can have children. Before, the user navigated to edit site

- Edit site was moved to actions list, as the first element

- There was an issue where, if the user created a site in child sites view, the site was created at top level. This is now fixed in this PR

Just let us know if you need any more info, and we'll be happy to help out.

Thanks for the time

**Comment by brianwulbern** [comment]
@ealonso @jkappler @evannagayama 

Looking into the test failures now :)

**Comment by brianwulbern** [comment]
I'm seeing a console error in this pull when navigating to Sites > Sites:

```
21:54:55,005 ERROR [http-nio-8080-exec-8][IncludeTag:128] Current URL /group/control_panel/manage/-/sites/sites?p_p_auth=7mVGyIvK generates exception: PWC6033: Error in Javac compilation for JSP__PWC6197:
An error occurred at line: 32 in the jsp file: /site_columns.jspf_PWC6199: Generated servlet error:_method setHref in class com.liferay.taglib.aui.base.BaseATag cannot be applied to given types;_  required
: java.lang.String_  found: javax.portlet.PortletURL_  reason: actual argument javax.portlet.PortletURL cannot be converted to java.lang.String by method invocation conversion__PWC6199: Generated servlet e
rror:_view_005fentries_jsp.java uses unchecked or unsafe operations.__PWC6199: Generated servlet error:_Recompile with -Xlint:unchecked for details.__ [Sanitized]
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP__PWC6197: An error occurred at line: 32 in the jsp file: /site_columns.jspf_PWC6199: Generated servlet error:_method setHref i
n class com.liferay.taglib.aui.base.BaseATag cannot be applied to given types;_  required: java.lang.String_  found: javax.portlet.PortletURL_  reason: actual argument javax.portlet.PortletURL cannot be co
nverted to java.lang.String by method invocation conversion__PWC6199: Generated servlet error:_view_005fentries_jsp.java uses unchecked or unsafe operations.__PWC6199: Generated servlet error:_Recompile wi
th -Xlint:unchecked for details.__ [Sanitized]
        at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129)
        at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299)
        at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:625)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at com.liferay.portal.servlet.jsp.compiler.JspServlet.service(JspServlet.java:308)
        at com.liferay.portal.servlet.jsp.compiler.JspServlet.service(JspServlet.java:319)
        at com.liferay.portal.portlet.tracker.internal.PortletTracker$JspServletWrapper.service(PortletTracker.java:1427)
        at org.eclipse.equinox.http.servlet.internal.registration.EndpointRegistration.service(EndpointRegistration.java:153)
        at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:50)
        at com.liferay.portal.portlet.tracker.internal.PortletTracker$RestrictPortletServletRequestFilter.doFilter(PortletTracker.java:1462)
        at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
        at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45)
        at com.liferay.portal.portlet.tracker.internal.PortletTracker$RestrictPortletServletRequestFilter.doFilter(PortletTracker.java:1462)
        at org.eclipse.equinox.http.servlet.internal.registration.FilterRegistration.doFilter(FilterRegistration.java:121)
        at org.eclipse.equinox.http.servlet.internal.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:45)
```

**Comment by ealonso** [comment]
Resend here: https://github.com/evannagayama/liferay-portal/pull/526

**Pull request closed without merging**
