### PR TITLE
master-qa-19907

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-19907

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@anthony-chu can you look into this and retest/fix?

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33201

**Pull request closed without merging**
