### PR TITLE
LPS-61489 Asset Publisher - configuration

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

Could you please take a look at poshi errors? I think more of then are related with the change from a checkbox to a toggle-switch.

Regards,
Eudaldo.

**Comment by ealonso** [comment]
cc @juliocamarero

**Comment by ealonso** [comment]
ci:retest

**Comment by koor4356** [comment]
@ealonso @juliocamarero I will look into these test failures. Thanks!

**Comment by juliocamarero** [comment]
thank you @koor4356 !!

**Comment by koor4356** [comment]
Hey @ealonso, @juliocamarero, I have rebase issue with this pr. Can someone take a look please?

{code}
git rebase master LPS-61489
First, rewinding head to replay your work on top of it...
Applying: LPS-61489 XSL - configuration
Applying: LPS-61489 Site Navigation - configuration
Applying: LPS-61489 Site Navigation Menu - configuration
Using index info to reconstruct a base tree...
M	modules/apps/site-navigation/site-navigation-menu-web/src/main/resources/META-INF/resources/configuration.jsp
Falling back to patching base and 3-way merge...
Auto-merging modules/apps/site-navigation/site-navigation-menu-web/src/main/resources/META-INF/resources/configuration.jsp
CONFLICT (content): Merge conflict in modules/apps/site-navigation/site-navigation-menu-web/src/main/resources/META-INF/resources/configuration.jsp
Failed to merge in the changes.
Patch failed at 0003 LPS-61489 Site Navigation Menu - configuration
The copy of the patch that failed is found in:
   /home/koor/private/liferay-portal-master/.git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".

{code}

**Comment by ealonso** [comment]
Hey @koor4356,

Please take this one: https://github.com/evannagayama/liferay-portal/pull/354

**Pull request closed without merging**
