### PR TITLE
master-bw-134

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-14592

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by evannagayama** [comment]
Pull request submitted to https://github.com/koor4356/liferay-portal/pull/12. <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by evannagayama** [comment]
ci:stop

**Comment by evannagayama** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by evannagayama** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38698

**Pull request closed without merging**
