### PR TITLE
LPS-60834 Lexicon pagination shows always on the bottom. We should ignore this property, otherwise we might end up with no pagination at all

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@jbalsas Hey Chema sorry I got to this late, but there's a UI issue with the card drop down. Can you fix it and send it again? Thanks!

selection_006

**Comment by jbalsas** [comment]
Thanks a lot, @evannagayama!

Resent to Brian https://github.com/brianchandotcom/liferay-portal/pull/32873

**Pull request closed without merging**
