### PR TITLE
LPS-61176 Uses toggle-switch

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by evannagayama** [comment]
ref: https://github.com/evannagayama/liferay-portal/pull/308

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33351

**Comment by evannagayama** [comment]
@ealonso I think this PR causes a bug. After I fixed many of the functional issues I ran into this issue. Could you please fix it and send again? Thanks

https://gist.github.com/evannagayama/2d95cfb97917e3ef386f

**Comment by evannagayama** [comment]
anim

**Comment by ealonso** [comment]
see https://github.com/juliocamarero/liferay-portal/pull/3849

**Pull request closed without merging**
