### PR TITLE
LPS-62783 Adds portal-service to gradle

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

We've removed the link to see the entity directly into the recycle bin, because it not make sense. If you want do that now, you should click on the recycle bin link and then click on the entry.

removed link



Could you please take a look at poshi errors?

Thanks!!!

**Comment by koor4356** [comment]
@ealonso I will look into posh failure on this pr. Thanks!

**Comment by koor4356** [comment]
@ealonso I've looked into this poshi issue.There is no information message after moving article or folder into the recycle bin. Can you please look into this? We will fix poshi failures after info message is fixed.

Thank you!
gifrecord

**Comment by ealonso** [comment]
Hey @koor4356 @evannagayama 

The poshi erros were my fault, sorry for that, I've sent the pull to Brian again, see: https://github.com/brianchandotcom/liferay-portal/pull/35766, and everything is fine now.

Regards,
Eudaldo

**Comment by koor4356** [comment]
Thank you, Eudaldo. I saw that it is passed :)

**Pull request closed without merging**
