### PR TITLE
LPS-62818 Moves layout form navigator entries to their category

### PR DESCRIPTION
**Pull request by ealonso**
Hey @evannagayama,

We've organized the sections from edit layout into different categories. Please check the new division of categories and sections on the following screenshot:

edit page - ai

Could you please take a look at poshi errors?, you can check here the poshi errors: https://github.com/brianchandotcom/liferay-portal/pull/35372

Thanks you very much!!!

### CODE REVIEW

**Comment by evannagayama** [comment]
@anthony-chu can you look into this and make test fixes? Thanks!

**Comment by anthony-chu** [comment]
ci:retest the failures look different between this PR and the original PR to bchan.

**Comment by ealonso** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed here: https://github.com/evannagayama/liferay-portal/pull/486

**Pull request closed without merging**
