### PR TITLE
master-lps-61127

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-61127

### CODE REVIEW

**Comment by anthony-chu** [comment]
@carloslancha 

This is a rebase of #362.

**Comment by evannagayama** [comment]
@koor4356 can look into this pr and make any changes necessary? Thanks!

**Comment by koor4356** [comment]
Thank you, I will look at this after analysis today.

**Comment by koor4356** [comment]
@carloslancha I've made test fixes and pushed this to @evannagayama here https://github.com/evannagayama/liferay-portal/pull/375. Thank you.

**Pull request closed without merging**
