### PR TITLE
LPS-62012 Move "Add Web Content" button

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, 

this pull moves the "Add" web content button from the Web Content Display to the topper. 

I have added the qa-id --> addButton to the button that opens this menu. This button is also in other portlets (document library, blogs, bookmarks...) so maybe you can reuse an existing macro or update it (all of those have the qa-id now).

welcome_-_liferay

thanks a lot!

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
This is likely failing due to known start-up issue caused by https://github.com/liferay/liferay-portal/commit/d992d839572c70e1e93be6c97b1566069941a69f

After this <a href="https://github.com/brianchandotcom/liferay-portal/pull/34330">pull</a> is merged please re-run this particular pull request.

Sorry for the inconvenience.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by evannagayama** [comment]
Awesome, thanks for adding the data-qa-id as well! I'll work on this today.

**Comment by evannagayama** [comment]
@juliocamarero I'm having some rebase issues. Can you rebase it and send again? Thanks

**Comment by juliocamarero** [comment]
Hey @evannagayama, 

I just rebased and pushed the code.

thanks!

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Thanks @juliocamarero I'll take a look. Just wondering, there were more commits before, but now I only see one. Is that ok? Thanks!

**Comment by evannagayama** [comment]
This is what it looks like right now. The add button on the bottom is gone, but not showing up in the portlet header.
wcdadd

**Comment by juliocamarero** [comment]
Hey @evannagayama 

you have discovered an issue when there is only 1 web content structure. @epgarcia will resend you the pull tomorrow fixing that.

Thanks!

**Comment by epgarcia** [comment]
See evannagayama/liferay-portal/pull/403.

Thanks!

**Comment by evannagayama** [comment]
Thanks guys!

**Pull request closed without merging**
