### PR TITLE
master-qa-20163

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-20163

### CODE REVIEW

**Comment by evannagayama** [comment]
@koor4356 

1. I believe these 2 macro commands are duplicates: SitePage#deleteSitepagesPG and Page#tearDownPG. Could you choose one to use and delete the other?
2. Could you also remove the navigation (ie Page#openURL/ProductMenu#gotoSite) and place it outside of the macro command, into the testcase? We should try to not have navigations inside the macro commands.

Let me know if you have any questions

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33529

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33587

**Pull request closed without merging**
