### PR TITLE
master-qa-7737

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-7737

### CODE REVIEW

**Comment by evannagayama** [comment]
@brianwulbern, did you mean to add this commit: LRQA-7734 Turn tests off? Also does the test assert somehow that the fields are nested?

**Comment by brianwulbern** [comment]
@evannagayama

Yeah, I forgot to add the assert at the end, but just added it in this rebase.  Thanks!

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@kenjiheigel

I added NESTED_FIELD to CPWebcontentAddwebcontent.path for this test to work.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/209

**Pull request closed without merging**
