### PR TITLE
LPS-61501 add qa-id

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @evannagayama 

I think this pull fails because I have slightly changed the html for "public pages" or "private pages". We should make it more robust. I have added some qa-ids for it. Would those be enough?

thanks!

welcome_-_liferay

**Comment by evannagayama** [comment]
Hey @juliocamarero thanks for sending this. I think it looks much better! I have found 1 bug and have a few suggestions.

Bug:
1. The Private Pages edit cog in Firefox 38 seems to be offset (it appears below the line)

Suggestions:
1. Could you move the data-qa-id='publicPages' up to the "span" instead of the "a" tag? It will make it easier to select the following plus and cog icons.
2. Could we have the product menu stay open when switching between public & private pages? I think that a user will lose context and it would be annoying to have to navigate back to the pages after switching.
3. Could we add a data-qa-id for the add page plus button and cog button? A bigger issue that we can discuss more about is that the new svg icons are not very good locators. Even with a new locator it will be pretty ugly like this //*[@data-qa-id='publicPages']//*[name()='svg'][contains(@class,'icon-plus')]

**Comment by evannagayama** [comment]
pages

**Comment by evannagayama** [comment]
pages

**Comment by evannagayama** [comment]
compass

Compass Bug

**Comment by evannagayama** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Hi Evan, 

the first css issue I will fix later since I still need to change many css in this UI.

I have fixed the issue with the sites button (good catch! :)

I have added the following qa-ids to cover all the links in that area. Let me know if you need more.

thanks!!

welcome_-_liferay_and_downloads

**Comment by juliocamarero** [comment]
Regarding this one: 

"Could we have the product menu stay open when switching between public & private pages? I think that a user will lose context and it would be annoying to have to navigate back to the pages after switching"

I can not reproduce it :(

Can you give me the steps you follow to reproduce that? thanks!

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@juliocamarero thanks for fixing those things! I checked right now and the last issue you asked about is also fixed! I'll fix the paths once the retest finished. Thanks!!!

**Comment by juliocamarero** [comment]
Awesome!!! Thanks a lot! :+1:

**Comment by evannagayama** [comment]
Pushed to Julio.
https://github.com/juliocamarero/liferay-portal/pull/3889

**Pull request closed without merging**
