### PR TITLE
master-lps-62997

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LPS-62997

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama @carloslancha 
Carlos, I tried to rebase your branch, but got conflicts.  So I just sent a pr on top of your branch where it was.

**Comment by evannagayama** [comment]
@carloslancha can you rebase with brian's fixes and push it again? Thanks!

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by evannagayama** [comment]
new pr here: https://github.com/brianchandotcom/liferay-portal/pull/35848

**Pull request closed without merging**
