### PR TITLE
master-lps-60646

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-60646

### CODE REVIEW

**Comment by anthony-chu** [comment]
This is a resend of #263, and it introduces a new set of paths for each Lexicon view, beginning with Card.path. I've talked with Kenji to make sure that this is going in the right direction.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
@ealonso There's a compile error on this pull request. Can you please take a look at it? Thanks!

**Comment by ealonso** [comment]
Hey @evannagayama @anthony-chu,

Resend here: https://github.com/evannagayama/liferay-portal/pull/269

**Comment by evannagayama** [comment]
new pull https://github.com/evannagayama/liferay-portal/pull/269

**Pull request closed without merging**
