### PR TITLE
LPS-60407 new icons for Control Menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hey @evannagayama 

this pull changes the icons in the control menu and it breaks the tests because you were using the old icon for the selector.

As we discussed, I have applied the qa-id pattern to the whole control menu so that now you can base the selectors and that and become independent of the implementation. There is a wrapper of these links with qa-id=controlMenu and then you can see the rest in the picture.

Let me know if I can help you or I missed anything.

thanks a lot!!

home_-_intranet_-_liferay

**Comment by anthony-chu** [comment]
Hi @juliocamarero I'll look into the test fixes for this pull request.

**Comment by anthony-chu** [comment]
New pull request sent #307

**Comment by anthony-chu** [comment]
Resubmitted here: #309.

**Pull request closed without merging**
