### PR TITLE
almost ready pull for the tree of pages

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by evannagayama** [comment]
@koor4356, could you fetch this branch and make the initial test fixes? Thanks!

**Comment by juliocamarero** [comment]
ci:retest

**Comment by juliocamarero** [comment]
@evannagayama @koor4356 there were some changes in master that broke the pull. I have updated the pull with those changes and it seems to work again for me.

**Comment by juliocamarero** [comment]
ci:retest

**Comment by evannagayama** [comment]
Closing this pr, as there is an updated one: https://github.com/brianchandotcom/liferay-portal/pull/32156

**Pull request closed without merging**
