### PR TITLE
master-qa-9441

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-9441

### CODE REVIEW

**Comment by evannagayama** [comment]
Pushed back to BWul

1. Combine these 2 commits
LRQA-9441 Add locator to optimize for loop
LRQA-9441 Optimize Web Content and Category macros for faster for loops

2. I don't understand some of the logic/naming. 
For example this commit "LRQA-9441 Optimize Web Content and Category macros for faster for loops" only optimizes 1 macro and the others are newly added. This commit "LRQA-9441 Add locator and macro for Vocabulary view in Web Content" seems to edit a macro that you just added?

Maybe one way to order them is to add commits that are for the first testcase then add commits for the second testcase. There are probably other ways too, right now it's just hard to understand how the commits relate to one another in a logical order.

3.  For this commit "LRQA-9441 Add test to view Vocabularies while adding Web Content", I don't think the MathUtil is necessary. It works, but you could just use a for loop. Also I'm not sure if you need to, but the test isn't viewing the Category while adding the WC. If you don't need to you could also just have all the categories be named the same thing.

**Comment by brianwulbern** [comment]
@evannagayama 

1. I would combine them, and still can, but the second of those commits is already optimizing two separate macros which will be utilized in:
LRQA-9441 Add test to view multiple Categories in Web Content

So it would be adding a third logical change into a commit that already has two.

2a. "LRQA-9441 Add test to view multiple Categories in Web Content" optimizes the Category macro, and adds a click at the bottom of the WebContent macro that will enable looping through that macro (in addition to the added macro).

2b. "LRQA-9441 Add locator and macro for Vocabulary view in Web Content", yeah, I can split this out and complete it in one commit.

3. MathUtil is tidier than a for loop, why not use it for cases we can use it on?  Also, we have other tests that view the Category while it's being added.

For now, I'll make the change in 2b.

**Comment by brianwulbern** [comment]
@evannagayama 

Please see the reordered commits above.  Hopefully it's a little bit clearer, now.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF For BWul.

#### 1. MathUtil vs for loop in this situation
"MathUtil is tidier than a for loop, but since we're not asserting the Category associated to it, we can just make it for loop through."

I don't think it's tidier. It takes more lines (~9 lines when I last checked the diff), requires more variables to be set, and is more complex than is needed for this, even with the Category. I would reserve using the MathUtil for more complex loops when its necessary. If you take a look at other uses of MathUtil you can see it's used for cases where the for loop wouldn't work.

#### 2. Rename commit "LRQA-9441 Optimize Category adding for faster for looping"
Renamed the commit to "LRQA-9441 Optimize Category#addCP macro to allow looping". I did this because from what I understand it isn't making the loop faster, but enabling the macro to be able to do a loop.

#### 3. Remove commit "LRQA-9441 Enable faster looping in Web Content Category viewing" and move loop into macro level
Put the loop into the viewCategorizationCategoryCP macro. Instead of looping at the testcase I moved it into the macro level. It makes it cleaner and doesn't run into the navigation issue. Because of this change I removed the commit.

#### 4. Rename the last macro and test commits just to make them more simple.
The line limit I think is 70. In general I think shorter and clear commit messages are good. This is more of just a personal preference I think.

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/301

**Comment by brianwulbern** [comment]
@evannagayama 

1. It looks like I've created a miscommunication in my wording.  I'm aware that MathUtil is more sophisticated than the for loop (I wrote the one in Portlet.macro that I copied for this, and subsequently switched for the for-loop).  As we discussed, there is no need to assert the Category, so there's also no need to assert a set of two unique, iterating variables.  In cases where multiple iterating variables are needed, the MathUtil is an elegant (and tidy) solution.  I hope this clears up my miscommunication. :)

**Comment by evannagayama** [comment]
I'm pretty sure I understood what you were saying and are now saying, but still think it was better to use the for loop then and now. In the previous solution (asserting the category) I believe you could have used a for loop because it could have been simplified to use one variable rather than "two unique, iterating variables". That's what I was referring to before and why I recommended the for loop. Let me know if you want me to show it to you; it might be easier to see it together.

**Pull request closed without merging**
