### PR TITLE
LPS-60244 ant format-source

### PR DESCRIPTION
**Pull request by adolfopa**

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey @evannagayama, @koor4356, for some reason the tests we should have fixed are still failing now... could you please take a look?

Thanks!

**Comment by jbalsas** [comment]
Oh... wait, maybe @adolfopa changes fixed that... if they pass, please, forward it to brian...

Thanks!

**Comment by adolfopa** [comment]
ci:retest

**Comment by evannagayama** [comment]
@koor4356 can you take a look at this and fix any tests needed? Thanks!

**Comment by koor4356** [comment]
@adolfopa @jbalsas I've pushed to @evannagayama here https://github.com/evannagayama/liferay-portal/pull/581.

**Pull request closed without merging**
