### PR TITLE
master-qa-13890

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-13890

### CODE REVIEW

**Comment by brianwulbern** [comment]
@kenjiheigel - here are some new locators in old paths

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
@BWul, Please fix this pr, update, and trigger the retest again. Thanks

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed back to BWul.
1. In the deleteCP there is no variable for deleteMethod? Could you look into this.
2. In Tag.macro mergeMultipleTags the confirmation message makes the test less flexible. Should it be set in the testcase?

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/58

**Pull request closed without merging**
