### PR TITLE
LPS-60742 Adapt styles to lexicon and uses aria instead of legend and fielset

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

Could you take a look at poshi errors?

Thanks!!!!

**Comment by evannagayama** [comment]
@brianwulbern can you look into this one and make any needed test fixes? Thanks!

**Comment by brianwulbern** [comment]
@evannagayama @ealonso 

Yep, I'm on it. https://issues.liferay.com/browse/LRQA-19774

**Comment by brianwulbern** [comment]
@ealonso @evannagayama 

I fixed the "Add Page" locator issue.  But there's a "TypeError: e is null" getting thrown in the browser when trying to add a Category - this also blocks the User from creating a Category, so all of the Category-related tests will fail on this.

Can you look into it when you have a chance?

Thanks!

**Comment by brianwulbern** [comment]
typeerror_with_categories

**Comment by brianwulbern** [comment]
@ealonso 
After you fix for the TypeError I showed above, the tests should be clear :)

I pushed the fix for the page issues to you here:
https://github.com/ealonso/liferay-portal/pull/562

**Pull request closed without merging**
