### PR TITLE
LPS-61029 Uses lexicon icon into icon menu

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @anthony-chu, @evannagayama, @koor4356, @brianwulbern

Could anyone please take a look to the poshi erros?  Sorry for cc's to everyone, I don't know who is working today in LA office

Thanks!!!

**Comment by ealonso** [comment]
I've replace some old icons for new lexicon icons. In some cases, the icon-* class was replaced by lexicon-icon-*, in other cases the icon is deferent, so for those cases you need to change the css class.

**Comment by koor4356** [comment]
@ealonso I will look at it after ci:test checked.

**Comment by evannagayama** [comment]
Koor pushed test fixes here: https://github.com/evannagayama/liferay-portal/pull/302

**Pull request closed without merging**
