### PR TITLE
master-qa-21511

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-21511
https://issues.liferay.com/browse/LRQA-21505
https://issues.liferay.com/browse/LRQA-21506
https://issues.liferay.com/browse/LRQA-21545

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35146

**Pull request closed without merging**
