### PR TITLE
LPS-62898 new site selector

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, 

Brian says this break a lot of tests... maybe other teams' tests were using the previous site selector?

### CODE REVIEW

**Comment by juliocamarero** [comment]
@evannagayama I have rebased the pull. thanks!

**Comment by evannagayama** [comment]
@juliocamarero sorry there were some tests using it. I'm not sure why the first pr didn't pick it up. I'll make the changes. Thanks!

**Comment by juliocamarero** [comment]
Thank you Evan! :+1:

**Comment by evannagayama** [comment]
@juliocamarero could you rebase this again? Thanks!

**Comment by juliocamarero** [comment]
@evannagayama rebased! :+1:

**Comment by juliocamarero** [comment]
@evannagayama fixed! :+1:

**Comment by evannagayama** [comment]
@juliocamarero I built, but now there is a console error when opening the product menu https://gist.github.com/evannagayama/8f576b4b51adf4b44a64. Also the Site Selector is missing and doesn't display at all.
selection_026

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35821

**Pull request closed without merging**
