### PR TITLE
master-qa-14528

### PR DESCRIPTION
**Pull request by kmaria**
Hi Evan,

please see https://issues.liferay.com/browse/LRQA-14528

Cheers,
Maria

### CODE REVIEW

**Comment by evannagayama** [comment]
Hey Maria I had a few questions and revisions;
1. For the STAGING_BUTTON could you erase the space in this path: <td>//a[contains(.,' Staging')]</td>
2. In the Staging.macro is there a reason it has to be an AssertClick#assertPartialTextClickAt? I put the AssertClickNoError because many of the tests were running into random javascript errors at that step. The AssertClickNoError ignores those so that it can keep running in jenkins. Maybe you can just change it to a ClickNoError instead?
3. In the tests you added a Page#gotoPagesCP right after a Page#gotoPG which should already work. Could you take out the unnecessary Page#gotoPagesCP that are set?

Please let me know if you have questions and when you have updated the pr. Thank you

**Comment by kmaria** [comment]
Hi Evan,

1. fixed
2. changed, thank you for the note
3. I need Page#gotoPagesCP instead of Page#gotoPG in the cases where Staging#configurePublishToLive is called. Application is changed so that publishing can be configured on CP only. Unnecessary Page#gotoPGs are removed.

Thanks.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Please fix errors and update. Thank you.

**Comment by kmaria** [comment]
Fixed. Thank you

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/51

**Pull request closed without merging**
