### PR TITLE
LPS-63345 buildLang

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey @evannagayama,

I've renamed 'Look and Feel' for 'Look and Feel Configuration'.

Could you please take a look at poshi errors?

Thanks!!!!

**Comment by evannagayama** [comment]
Hi @ealonso,

It looks like the ui is wrong, it reads "look-and-feel-configuration" instead of "Look and Feel Configuration". Could you update this? Thanks

selection_033

**Comment by evannagayama** [comment]
@ealonso I fixed the tests to assert "Look and Feel Configuration" and pushed it to my local branch here: https://github.com/evannagayama/liferay-portal/commits/master-lps-63345

You can fetch it then fix the ui and it should pass. Thanks!

**Comment by ealonso** [comment]
Resend here: https://github.com/evannagayama/liferay-portal/pull/549

**Pull request closed without merging**
