### PR TITLE
master-qa-18709

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-18709

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF For Achu.
Removed now unused macro
Removed unused star ratings

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31354

**Pull request closed without merging**
