### PR TITLE
master-lps-62270

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21473

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama 

The test issue got resolved, minus the failing test in every pull (ExportImport#ExportImportSiteWithChangedSiteDefaultLanguage)

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34926

**Comment by evannagayama** [comment]
@brianwulbern can you fix rebase errors and resend? Thanks

**Comment by brianwulbern** [comment]
@evannagayama 

On it.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama 

Here's the link to the retest results from my comment above: https://test-1-7.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1943/jenkins-report.html

**Comment by brianwulbern** [comment]
@evannagayama 

All good!

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34977

**Pull request closed without merging**
