### PR TITLE
master-qa-19296

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LRQA-19296

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@anthony-chu can you look into this and retest or fix it? Thanks

**Comment by anthony-chu** [comment]
cc @xbrianlee

I've used Navigator#gotoNavItem to navigate to External Services, since this macro does a check to make sure, after navigating, that portal is on the correct nav-item.

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34973

**Pull request closed without merging**
