### PR TITLE
LPS-60244 Add lang key

### PR DESCRIPTION
**Pull request by jbalsas**
Test is failing probably because of this title locator https://github.com/jbalsas/liferay-portal/blob/master/portal-web/test/functional/com/liferay/portalweb/portal/util/liferayselenium/WebDriverHelper.java#L547

Couldn't we use `id` instead?

### CODE REVIEW

**Comment by evannagayama** [comment]
@koor4356 could you take a look at this and make test fixes? Thanks!

**Comment by koor4356** [comment]
@jbalsas I will look into this poshi errors. Thank you!

**Comment by koor4356** [comment]
@jbalsas QA engineering team is updating poshi and this should fix those errors. It may take 2 or 3 days. Here is the QA ticket https://issues.liferay.com/browse/LRQA-19127 to follow. I will revisit  this if there are more failures.

**Comment by kenjiheigel** [comment]
@jbalsas, I sent a pull for this: https://github.com/lesliewong92/liferay-portal/pull/22. Hopefully it gets merged tomorrow. For changes to our WebDriver infrastructure a new osgi jar for poshi-runner will need to be released and updated for our tests. This process takes a day or two, which will be after my commit goes in. Let us know if you have any questions! 

Sorry I just got around to updating this now, I know we talked about it a few months back.

**Comment by jbalsas** [comment]
Hey guys!

Thanks everyone for the quick response and the help! 

Should I close this one and resend after your WebDriver changes have been merged, or will you be taking care of it?

Thanks again!

**Comment by kenjiheigel** [comment]
@jbalsas, we can just leave this pull open for now, for visibility. Koor will need to update the tests after the WebDriver changes anyways, so he can send a new pull to Evan with your changes + test fixes once the new jar is ready, and then close this pull at that time.

**Comment by jbalsas** [comment]
Hey @kenjiheigel, @evannagayama, @koor4356, what's the status of this? Are the WebDriver changes in? Is someone working on the test fixes?

Let me know if there's something I could do.

Thanks!

**Comment by kenjiheigel** [comment]
The WebDriver changes are in, but we need to await the release of a new jar:
https://issues.liferay.com/browse/LRQA-21585

It should go in later today though.

**Comment by koor4356** [comment]
Hey @jbalsas, l will start making test fixes today. Thank you!

**Comment by michaelhashimoto** [comment]
Hi @jbalsas!

We are still adding in the new release of poshi here:
https://github.com/pyoo47/liferay-portal/pull/27

Sorry for the delay.

It should be in by the beginning of next week.

Thanks!

**Comment by jbalsas** [comment]
Hi guys, thanks a lot for working on this!

Do we have any estimates as to when are we going to be able to send this in?

**Comment by pyoo47** [comment]
I'm going to review this today so I can push to bchan as soon as possible.

Peter

**Comment by koor4356** [comment]
@jbalsas, test fixes has been pushed to @evannagayama here https://github.com/evannagayama/liferay-portal/pull/544. Thank you!

**Comment by jbalsas** [comment]
Thanks a lot, guys!

**Pull request closed without merging**
