### PR TITLE
LPS-19777: Sites are deleted in "tear-down" tag

### PR DESCRIPTION
**Pull request by asungutierrez**

### CODE REVIEW

**Comment by evannagayama** [comment]
@asungutierrez there's a rebase error. Could you rebase this and ressend so the tests will run? Thanks!

**Comment by evannagayama** [comment]
@asungutierrez I was able to rebase the branch and look at the issues. There have been some changes since you last updated, that conflicted. If you work on branch for an extended period of time it's probably best that you update and rebase often. If you rebase it with thew new site selector macro, I believe the test should pass. I didn't see the other issue with the success message you were referring to. Thanks!

**Comment by evannagayama** [comment]
ci:retest

**Comment by asungutierrez** [comment]
@evannagayama thank you very much for update!

**Comment by evannagayama** [comment]
Closing per discussion. Thanks Asun

**Pull request closed without merging**
