### PR TITLE
LPS-62065 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by evannagayama** [comment]
@ealonso thanks for updating this.

I messaged Julio, but I think he was already gone. Regarding the bug that allows the product menu and control menu to open at the same time. This causes many tests to fail and we have to add a workaround. Our concern is that we'll just have to fix our tests again once it's fixed.

Would it be possible for you to push this to whoever is going to make the other changes and have the final changes pushed in at one time?

**Comment by evannagayama** [comment]
re: https://github.com/evannagayama/liferay-portal/pull/462

**Comment by ealonso** [comment]
Hey @evannagayama,

I've send the pull request to Patrick see: https://github.com/pat270/liferay-portal/pull/157

**Comment by evannagayama** [comment]
Thanks @ealonso!

**Comment by juliocamarero** [comment]
https://github.com/evannagayama/liferay-portal/pull/479

**Pull request closed without merging**
