### PR TITLE
LPS-62640 Remove button to edit the current page from the Control Menu

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan,

this pull removes the edit page link at the top of the page. Now users need to use the cog icon from the tree.

Do you want me to add a qa-id for each edit link?

thanks!

welcome_-_liferay

### CODE REVIEW

**Comment by evannagayama** [comment]
@juliocamarero one issue I ran into is that the user can no longer delete a page from live. This happens because there is no edit page icon. Before the user could navigate through the edit icon at the top, but now it's not possible. Let me know if this is ok?

**Comment by juliocamarero** [comment]
Good point! We have another pull coming that adds a delete icon in the tree in staging... we can wait until that one if you want to merge this one. 

Thanks!

**Comment by evannagayama** [comment]
Sounds good, I'll just push this in for now and we can make the change to the staging test on the next one. Thanks!

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35247

**Pull request closed without merging**
