### PR TITLE
master-qa-20322

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-20322

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33529

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33565

**Pull request closed without merging**
