### PR TITLE
LPS-63581 - Apply CSS only to sidenav-menu

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@juliocamarero @jonmak08 

This is failing the tests because the change caused the div to be bigger than the product menu. Anything behind the "border" cannot be interacted with. Here's a screenshot of the issue.

pmsize

**Comment by jonmak08** [comment]
You can close this pull request.  I will resend a new fix.

**Comment by evannagayama** [comment]
Ok thank you!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/ealonso/liferay-portal/pull/678

**Pull request closed without merging**
