### PR TITLE
LPS-62149 Change markup of Control Menu

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @evannagayama 

could you please review this pull? @asungutierrez has tried to fix some of the errors she found.

thanks!

### CODE REVIEW

**Comment by anthony-chu** [comment]
@juliocamarero @asungutierrez thanks! I'll look into the test results!

**Comment by anthony-chu** [comment]
@juliocamarero

missing-maxagetimedescription

It looks like the recycle bin tooltip message is missing the trashEntriesMaxAgeTimeDescription and is causing CPWiki#DeleteWikiNode to fail (there is a macro that asserts the Recycle Bin tooltip message). Can you look into it? Thanks!

**Comment by juliocamarero** [comment]
@anthony-chu you are right... I can reproduce that... how weird! I will have a look tomorrow... thanks!

**Comment by juliocamarero** [comment]
Good catch @anthony-chu!

that should be fixed here: https://github.com/brianchandotcom/liferay-portal/pull/34880 

I just sent to Brian but I may have to close it and send it back to you.

thanks!

**Comment by juliocamarero** [comment]
Continues here :(

https://github.com/evannagayama/liferay-portal/pull/440

**Pull request closed without merging**
