### PR TITLE
LPS-62065 new panels for simulation and add apps

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, @koor4356

closing one panel while the others open seems to be very complex and we may not even do it for the release.

Therefore, we would need to merge this pull that just uses the new panels.

Let me know if we can help you,

thank you!

cc @ealonso

### CODE REVIEW

**Comment by evannagayama** [comment]
Thanks @juliocamarero. @koor4356 can you look into this and make sure everything is good? Thanks!

**Comment by koor4356** [comment]
Thank you, guys, I will look into this.

**Comment by evannagayama** [comment]
selection_001

**Comment by evannagayama** [comment]
@juliocamarero it seems there are 2 "bugs"
1. The panels can both be open at the same time. This one you have already mentioned, but I want to confirm you're ok with this and that this will be the intended function moving forward.
2. The accordion function where opening one panel and the rest closing has been removed. Now all the panels can be opened at the same time.

It might be easiest to talk about this in a call. Let me know if you are available tomorrow. Thanks!

**Comment by evannagayama** [comment]
@juliocamarero as discussed, #1 is intended, and is a "nice to have" fix for the future. We'll wait on you to see if #2 is an actual bug. Once that is cleared/fixed we'll push this in. Thanks!

**Comment by juliocamarero** [comment]
Hey Evan, 

I have tested the branch and everything works as expected to me...

1. The accordeon in the product menu seems to be fine
2. The accordion in the Add Content/Apps seems to be fine
3. The list of apps is not an accordion, just regular panels.

evan-panels

Maybe there was another bug when you tested the branch? I have rebased on top of master and pushed here.

**Comment by evannagayama** [comment]
@koor4356 can you rebase and check this function out? If it's fixed at head we can just push it in. Let me know, thanks!

**Comment by koor4356** [comment]
Thanks guys! will double check.

**Comment by koor4356** [comment]
Hey @juliocamarero and @evannagayama,
Here is my finding after rebasing on head.
When you expand pages and try to expand contents, should pages collapse or stay expanded? 
gifrecord

**Comment by evannagayama** [comment]
Oh I see, what the difference is. Only the panels have the accordion function. Inside the panels, all the "sub-panels" can be open at the same time. Ok I'll push it in. Thanks!

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35488

**Comment by juliocamarero** [comment]
Thanks a ton guys!! :+1:

**Comment by evannagayama** [comment]
Not sure why it passed on here before.


https://github.com/brianchandotcom/liferay-portal/pull/35488
It fails a lot of tests due to 2 reasons:
1. The drag and drop feature doesn't work for dm because of sizing issues. (just add the 1 column setting like before)
2. The application menu needs to wait until it's loaded.

@koor4356 can you make these fixes? Thanks

**Comment by evannagayama** [comment]
https://github.com/evannagayama/liferay-portal/pull/487

**Pull request closed without merging**
