### PR TITLE
LRQA-21152 Hardcode 'Liferay' Site in generic Page teardown

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama @juliocamarero 

The PortalconfigurationUsecase#DefaultPortalLandingPage is a fluke.  But CPSitepages#DeleteSitePages is related to the changes, yet worked locally when I tested it.  I'll look at it again tomorrow.  Thanks!

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@juliocamarero @evannagayama 

I pushed a fix to make the test more stable here: https://github.com/evannagayama/liferay-portal/pull/412

It passed twice locally, so it should be good...

**Pull request closed without merging**
