### PR TITLE
master-qa-14713

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-14713

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
Expediting this pull because Evan's not here.

**Comment by brianchiu** [comment]
No test changes needed :)

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25271

**Comment by brianchiu** [comment]
@brianwulbern @evannagayama 

You can close this pull.

**Comment by brianwulbern** [comment]
@brianchiu 

Closing.

**Pull request closed without merging**
