### PR TITLE
master-lps-63004

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LPS-63004
https://issues.liferay.com/browse/LRQA-22131

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama 

There was a view.jsp file that got changed during SF.

**Comment by evannagayama** [comment]
@brianwulbern can you fix it and push again? Thanks

**Comment by brianwulbern** [comment]
mm, I didn't make any changes to jsp files?

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF for BWul.
I changed some of the macro + locators to use existing ones, so we don't add more.
See changes here: https://github.com/evannagayama/liferay-portal/commit/2af437eb11efc04839f4ba79c683fa3aaa722b4d

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36271

**Pull request closed without merging**
