### PR TITLE
master-qa-14790

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-14790

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianchiu** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/25368

**Comment by brianchiu** [comment]
@brianwulbern @evannagayama 

Please close.

**Comment by brianwulbern** [comment]
@brianchiu 

Closing.

**Pull request closed without merging**
