### PR TITLE
master-qa-18543

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-18543

### CODE REVIEW

**Comment by evannagayama** [comment]
@koor4356 

1. Why did you remove the error messages in DeleteNoLiferaySite? That macro seems to check that the user cannot deactivate the site. If you are able to do it now, it may be a bug, or if the functionality changed, it may not even be necessary to have this macro or test anymore. Can you check this and let me know? Thanks
2. In this commit "LRQA-18543 Remove viewSiteHierarchyInBreadcrumbPG from the test", I'm wondering again why you removed "Site#viewSiteHierarchyInBreadcrumbPG" and if it's a functional change or a bug.

Please check these 2 things and let me know if you have any questions. Thanks

**Comment by koor4356** [comment]
1. Hmm, There is a message lps ticket on the commit where I remove the
error that macro was checking. you should look at it and see the comment
Eudaldo made.

2. Breadcrumb is no longer a default an embedded portlet. If you like the
macro not to be removed, then we have to add a macro to Breadcrumb portlet
to the page. (I brought this up to on Monday.)

**Comment by evannagayama** [comment]
1. What ticket are you referring to?
2. I don't understand what you mean 100%. It seems to me that if we aren't asserting these things then we might as well not have this test, because it was written for these assertions.

I think it's easier to figure out in person and looking at the portal. I'll check with you tomorrow.

**Comment by evannagayama** [comment]
SF for KGai.
Just removed the test because the function has changed.

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/31078

**Pull request closed without merging**
