### PR TITLE
master-qa-21152-2

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21152

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama 

The poshi error is from a flaky test unrelated to the changes in the PR.  Thanks!

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34766

**Comment by evannagayama** [comment]
@brianwulbern can you add another macro to open the pages panel again. It seems sensitive and sometimes it doesn't stay open

**Comment by brianwulbern** [comment]
@juliocamarero @evannagayama 

Yep, I rebased the whole thing and re-submitted it here: https://github.com/evannagayama/liferay-portal/pull/423

**Pull request closed without merging**
