### PR TITLE
master-qa-22588

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-22588
https://issues.liferay.com/browse/LRQA-22589
https://issues.liferay.com/browse/LRQA-22478
https://issues.liferay.com/browse/LRQA-22464
https://issues.liferay.com/browse/LRQA-22463
https://issues.liferay.com/browse/LRQA-22274

### CODE REVIEW

**Comment by brianwulbern** [comment]
cc @brianchiu

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Nice fixes and clear commits, thanks!

Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36896

**Pull request closed without merging**
