### PR TITLE
LPS-62077

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LPS-62077

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by koor4356** [comment]
Hey @ealonso I've made test fixes on top of this https://github.com/evannagayama/liferay-portal/pull/400, but I have run into an issue. The warning message "Entries that have been in the Recycle Bin for more than 1 month are automatically deleted. Empty the Recycle Bin" is missing. Can you look into this, please?

The message on this image should display, but it is missing on the pull request. 

Thank you.


rb

**Comment by koor4356** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @koor4356,

I've moved the warning message to the portlet description.

From:

recycle_bin_-_liferay


To:

recycle_bin_-_liferay 2


Regards,
Eudaldo.

**Comment by koor4356** [comment]
Thank you, Eudaldo. I will look into this.

Koor!

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by ealonso** [comment]
Hey @evannagayama,

I think those errors are not related with this pull.

Thanks!!

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34743

**Pull request closed without merging**
