### PR TITLE
LPS-62106 only count direct memberships

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey @evannagayama,

this is a change in the logic for the count of members in sites. As you probably know, organizations and user groups can be members of a site too.

When we display the number of members we used to display the agregation of all users that were members for one or other reason. Since that had many innacurities and many performance issues we are not only showing the number of users explicitely added. There is a tooltip explaining this. The tests break because they expect a different number of members.

Can you have a look?

thanks a lot!

### CODE REVIEW

**Comment by evannagayama** [comment]
Hey @juliocamarero,

I've been looking into this PR and I have one question about Organizations. Before if you add an organization and org site in the site view it would display "1 Organization". Now it doesn't display anything. I think this is correct, but can you confirm? Thanks!

**Comment by evannagayama** [comment]
selection_023

**Comment by juliocamarero** [comment]
Hey @arbetts 

can you confirm if this is the expected behavior now? or it this a regression introduced by the pull?

thank you!

**Comment by arbetts** [comment]
the number is pulled straight from the mapping table groups_orgs so i would not expect the organization to show up for its own group. (since it is linked by the classNameId and classPK and not the groups_orgs table)

this is expected behavior, but i think we can change this if it seems wrong,

**Comment by evannagayama** [comment]
Thanks guys, I'll make the necessary changes to account for this behavior.

**Comment by evannagayama** [comment]
Pushed to Bchan.
https://github.com/brianchandotcom/liferay-portal/pull/34751

**Pull request closed without merging**
