### PR TITLE
LPS-62592 show loading icon in the panels (this commit will be reverted once the panels support this feature in lexicon)

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, 

this pull adds the loading icon to the right panels (simulator and add content/application).... it seems many tests break because they are doing something with the loading icon of the add application menu.

Could you please have a look?

thank you!

### CODE REVIEW

**Comment by anthony-chu** [comment]
@juliocamarero It looks like the failures are caused when the loading-animation is not destroyed after the panels are finished loading. The portlets assert that the loading-animation markup is removed after they have been completely loaded; however, it appears that the loading-animation in the panels is not getting destroyed after they finish loading. Can you take a look into this? Thanks!

**Comment by juliocamarero** [comment]
Hi @anthony-chu 

I have tested this and the behavior is correct. The problem is that the macro is finding other loading icons existing in the page. 

For example, the simulation menu has a loading icon that is removed once the panel is loaded. However, you still find that one when loading the add application panel.

One possible solution could be to search for the loading icon inside the panel only (is that an option?).

another option is to add qa-id to the body of the panels and just check that the body is loaded instead of check that the loading icon is not present.

Let me know which option you think is best,

thanks!

**Comment by evannagayama** [comment]
@brianwulbern can you finish this off? Thanks!

**Comment by brianwulbern** [comment]
@evannagayama @juliocamarero @anthony-chu 

Looking into it now :)

**Comment by brianwulbern** [comment]
This one worked locally.  I'm gonna see how the results turn out and investigate more if it's still problematic:
https://github.com/evannagayama/liferay-portal/pull/505

**Comment by juliocamarero** [comment]
Thanks a lot @brianwulbern !! 

https://github.com/brianchandotcom/liferay-portal/pull/35768

**Pull request closed without merging**
