### PR TITLE
LPS-60931 Site teams users icon

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by ealonso** [comment]
Hey Evan,

I've removed some information from descriptive view according lexicon design, so, this is the information that should be appear on descriptive view:

web_content_-_liferay

**Comment by ealonso** [comment]
If you want to see the poshi failures before the test finisth this is the pull that I sent to Brian https://github.com/brianchandotcom/liferay-portal/pull/32872

**Comment by evannagayama** [comment]
Perfect thank you!

**Comment by evannagayama** [comment]
Pushed here: Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32874

**Pull request closed without merging**
