### PR TITLE
LPS-63608 New UI for pages tree

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, 

these are the changes for the tree of pages, now all the actions are under the ellipsis menu (they all have qa-ids):
welcome2_-_liferay

Another big change is that if there aren't private pages, the link is not shown. 

pirvvv_-_liferay

In order to add private pages when you don't have any, since we don't have the private pages link, you need to add them from the ellipsis of the public pages.

pirvvv_-_liferay

Once you have both sets of pages, the link to add more private pages is again under the ellipsis menu of the private pages:

bla_-_liferay

I have added qa-id to all the ellipsis menu (publicPagesOptions, privatePagesOptions, pagesOptions). Let me know if you want to have the friendly url in each page ellipsis menu or something like that. Each option inside also has a qa-id (addChildPage, editPage, deletePage, addPublicPage, addPrivatePage).

### CODE REVIEW

**Comment by juliocamarero** [comment]
ci:retest

**Comment by evannagayama** [comment]
@juliocamarero Hey Julio I'm still working on this, but when I run ant format-source there's a change in layouts_tree.jsp and I'm not sure how it's supposed to be changed. Can you look into this? 

I'm hoping to get this done by eod tomorow. Thanks!

./modules/apps/web-experience-management/layout/layout-admin-web/src/main/resources/META-INF/resources/panel/app/layouts_tree.jsp

**Comment by juliocamarero** [comment]
yup, I just fixed that and pushed here :)

thanks!

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/37044

**Pull request closed without merging**
