### PR TITLE
master-qa-16309

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-16309

### CODE REVIEW

**Comment by evannagayama** [comment]
Pushed to KGai.
Add back in the assertextequals after the makevisible command

**Comment by koor4356** [comment]
ct:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/417

**Pull request closed without merging**
