### PR TITLE
pr-3807

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LPS-57564

### CODE REVIEW

**Comment by juliocamarero** [comment]
Hi guys, 

I check those 2 tests and both are test that needs to be updated:
- The SelectWebContent is trying to add a Page in the old way:
https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest%28master%29/builds/492/test-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=PGWebcontentdisplay%23SelectWebContent,label_exp=!master/functional-tomcat-mysql/4/index.html


- The AddBlogsEntrySiteRole is also going to the Site Administration and trying to click on a page (using the old tree) See the error after the 2 warnings:
est-portal-acceptance-pullrequest-batch%28master%29/AXIS_VARIABLE=CPRolesPGBlogs%23AddBlogsEntrySiteRole,label_exp=!master/functional-tomcat-mysql/3/index.html

Can you please prioritize this today? We are really close now!

Thanks a lot!

**Comment by koor4356** [comment]
Thank you, Julio. Yes, I missed those. I will look at them now.

Koor!

**Comment by juliocamarero** [comment]
Thank you!!

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
Acceptance tests should pass and the rest of the variables and site page navigation & add will be cleaned up on this ticket: https://issues.liferay.com/browse/LRQA-19573

**Comment by evannagayama** [comment]
Thanks Koor! Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32339

**Comment by juliocamarero** [comment]
Thanks a ton guys!!! That is awesome!!!! :+1:  :clap: :clap: :clap:

**Pull request closed without merging**
