### PR TITLE
master-lps-64215

### PR DESCRIPTION
**Pull request by evannagayama**
test

### CODE REVIEW

**Comment by evannagayama** [comment]
@ealonso there is a bug from this pr that the options menu expands outside of the page for the search portlet (and i'm assuming any portlet that is too close to the right side). Could you fix this and resend? Thanks!

offsetsearchoptions

**Comment by evannagayama** [comment]
@ealonso there is a bug from this pr that the options menu expands outside of the page for the search portlet (and i'm assuming any portlet that is too close to the right side). Could you fix this and resend? Thanks!

offsetsearchoptions

**Comment by ealonso** [comment]
Resend: https://github.com/evannagayama/liferay-portal/pull/648

**Comment by evannagayama** [comment]
ci:retest

**Comment by ealonso** [comment]
see: https://github.com/evannagayama/liferay-portal/pull/648

**Pull request closed without merging**
