### PR TITLE
master-lps-61140

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21351

### CODE REVIEW

**Comment by brianwulbern** [comment]
@carloslancha @evannagayama 

These errors are unrelated to the fixed tests.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/34747

**Comment by evannagayama** [comment]
@brianwulbern looks like a bug: https://github.com/brianchandotcom/liferay-portal/pull/34747. Can you check it? Thanks

**Comment by brianwulbern** [comment]
@evannagayama @carloslancha 

I looked into this some more, and it seems to be a bug with the Danger message on the third failed attempt to login.  Here's an animation of what it looks like (I already got locked out on the 9080 instance, so I just show that part last).  Since this isn't committed yet, I didn't make an LPS, just this gif.

thrice_crazy_warning

**Comment by evannagayama** [comment]
@carloslancha when you are able, can you make that fix and resend it to me? I'll close this for now, thank you.

**Comment by brianwulbern** [comment]
It says this in the last Danger message: "× Danger\x0a\x0a\x09\x09\x09\x09\x0a\x0a\x09\x09\x09\x09This\x20account\x20is\x20locked\x20until\x201\x2f21\x2f16\x206\x3a00\x20PM\x2e\x20Please\x20wait\x20until\x20the\x20unlock\x20date\x20or\x20contact\x20an\x20administrator\x20to\x20have\x20this\x20account\x20unlocked\x2e\x0a\x09\x09\x09"

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Here it is @evannagayama https://github.com/evannagayama/liferay-portal/pull/430

Thanks!

**Pull request closed without merging**
