### PR TITLE
master-lps-63052

### PR DESCRIPTION
**Pull request by evannagayama**
test

### CODE REVIEW

**Comment by evannagayama** [comment]
@juliocamarero thanks for making the fix. I fixed the message assertion and got rid of the back button assertion, so it should pass now. On this pr I found a new issue introduced. There is the leaf icon to right of the pages and it shifts the ui over so the cog icon is cut off. Can you take a look at this? Thanks

selection_032

**Comment by evannagayama** [comment]
ref: https://github.com/evannagayama/liferay-portal/pull/545

**Comment by evannagayama** [comment]
ci:retest

**Comment by juliocamarero** [comment]
Thank you Evan! The leaf issue is in master also, Eduardo created that regression but we are fixing it now :)

I have sent this pull to Brian https://github.com/brianchandotcom/liferay-portal/pull/36244

thanks a lot!!! :+1:

**Comment by evannagayama** [comment]
Ah ok I didn't realize that. Thanks!

**Pull request closed without merging**
