### PR TITLE
pr-315

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LPS-61127

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@koor4356 can you rebase and resend? Thanks

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by koor4356** [comment]
Hey @carloslancha , I made test fixes on top your pr-315 here: https://github.com/evannagayama/liferay-portal/pull/351. No success message when adding page variation on pull request. I've tested on http://master.liferay.org.es/ and there was a success message. Can you take a look at this please?

Ccing @juliocamarero and @evannagayama here. Thanks!.
The message should like this:
selection_002

**Comment by evannagayama** [comment]
ci:retest

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by carloslancha** [comment]
Hey @koor4356 I've taken a look and it's a js problem. I'm fixing it and I'll send it to you when finish. I've tried to rebase with master but there are conflicts, could you please rebase it and resend to me?

Thanks!

**Comment by evannagayama** [comment]
Hey @carloslancha Koor is out this week so Anthony will rebase it and send it to you. Thanks!

**Pull request closed without merging**
