### PR TITLE
master-lps-60407

### PR DESCRIPTION
**Pull request by anthony-chu**
https://issues.liferay.com/browse/LPS-60407

### CODE REVIEW

**Comment by anthony-chu** [comment]
ci:retest

**Comment by anthony-chu** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
@anthony-chu can you check why it's failing this test? It happened twice now.

**Pull request closed without merging**
