### PR TITLE
LPS-63004 SF

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by jkappler** [comment]
cc:/ @brianwulbern

**Comment by brianwulbern** [comment]
@ealonso @jkappler 

Thanks, guys, I'll have a look when it finishes.

**Comment by brianwulbern** [comment]
I don't think these are related to your changes.

**Comment by brianwulbern** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@ealonso @jkappler 

Looking at the other pulls in BChan's queue, it looks like something in this PR is causing the failures.

Any ideas about this one?

```
 * What went wrong:
     [exec] A problem occurred evaluating project ':portal-configuration:portal-configuration-module-configuration'.
     [exec] > Project with path ':portal:portal-metatype' could not be found in project ':portal-configuration:portal-configuration-module-configuration'.
```

**Comment by jkappler** [comment]
@evannagayama, please close this one. New one here for @brianwulbern : https://github.com/brianwulbern/liferay-portal/pull/125

**Pull request closed without merging**
