### PR TITLE
master-lps-62586

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21615

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama 

Missed an iframe, fixing...

**Comment by brianwulbern** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by brianwulbern** [comment]
That Poshi failure is a flaky test being looked in to: https://issues.liferay.com/browse/LRQA-21633

**Comment by evannagayama** [comment]
re https://github.com/evannagayama/liferay-portal/pull/457

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35216

**Comment by evannagayama** [comment]
SF For @brianwulbern.

1. I just replaced one more instance of the add entry.
2. I think one thing we should think about is if we need the LexiconEntry.macro. I'm not sure if it's helpful to add it into a macro, because it might just be creating more noise. Unless we're planning to use it everywhere. But we would need to consider why this is profitable or if it's just more confusing having 2 different ways to do it. We can revisit this later, just something we can think about. Thanks!

**Comment by brianwulbern** [comment]
@evannagayama 

Yeah, I thought it might be adding fluff to the macro layer, since some of the lexicon clicking is in 'navigator' macro blocks.  But if we combine all of them into an 'addSimple' (where clicking the + is enough) and an 'addChoice' (where you select an option afterwards), it would organize all of the same locators into one spot.  It would take some getting used to, but I think it could be cleaner that way, especially if the lexicon framework will be consistent.

**Pull request closed without merging**
