### PR TITLE
LPS-61825 build lang

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan, 

this pulls makes 1 test fail: PoshiRunner.test[CPSitepages#EditSitePage] - Poshi Report - Poshi Summary - Console Output

I think it's because I have modified the tooltip to edit a page to say just "Edit" instead of "Edit Page Name" to simplify the UI. I have seen you are using the tooltip message in the selector. Is there an alternative? do you need me to add other qa-ids for that?

thank you!

### CODE REVIEW

**Comment by koor4356** [comment]
@juliocamarero I will look into this poshi failure. Thanks!

**Comment by koor4356** [comment]
@juliocamarero I've made test fixes and pushed to @evannagayama here: https://github.com/evannagayama/liferay-portal/pull/436.

**Comment by evannagayama** [comment]
@juliocamarero, Koor changed it to use the a tag, the link. I think it's ok for now, because even with a data-qa-id, we would need to be specific about which page is clicked. Thanks!

**Comment by juliocamarero** [comment]
What If I include the page name also as part of the qa id? qa-id="editPageWelcome" ?

**Pull request closed without merging**
