### PR TITLE
LPS-62997 Apply lexicon to success message in trash when restore element

### PR DESCRIPTION
**Pull request by carloslancha**

### CODE REVIEW

**Comment by carloslancha** [comment]
Hi Evan, could you take a look to the poshi error PoshiRunner.test[RecyclebinUsecase#RestoreDMDocumentFromFolderCP] ?

Thanks!

**Comment by evannagayama** [comment]
@brianwulbern can you take a look at this and make test fixes? Thanks!

**Comment by brianwulbern** [comment]
@evannagayama @carloslancha 

I'm on it.

**Comment by brianwulbern** [comment]
@carloslancha @evannagayama 
See the fix here: https://github.com/evannagayama/liferay-portal/pull/512

**Pull request closed without merging**
