### PR TITLE
LPS-61029-1

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LPS-61029

### CODE REVIEW

**Comment by koor4356** [comment]
@ealonso, I've made the test fixes on here https://github.com/evannagayama/liferay-portal/pull/302.
Evan won't be back until Wednesday to review the test fixes.

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
This failure has nothing to do with this pull request.

**Comment by evannagayama** [comment]
ci:retest

**Comment by ealonso** [comment]
ci:retest

**Comment by evannagayama** [comment]
Will update/clean up the ellipsis locators later: https://issues.liferay.com/browse/LRQA-20234

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/33205

**Pull request closed without merging**
