### PR TITLE
master-qa-18339

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-18339

### CODE REVIEW

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF For KGai.
Just removed unnecessary line

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/32129

**Pull request closed without merging**
