### PR TITLE
master-qa-14152

### PR DESCRIPTION
**Pull request by kmaria**
Hi, 

https://issues.liferay.com/browse/LRQA-14152
references are fixed.

Cheers,
Maria

### CODE REVIEW

**Comment by evannagayama** [comment]
Hi Maria,

Sorry this has been a long process. There were more changes about the way we make tickets in Jira and our commit messages. It has been changed to just be the LRQA ticket. So for this pr the commit  messages would be: LRQA-14152 - paths, LRQA-14152 - macros, and LRQA-14152 - tests. Lawrence and BChiu are going to send out a forum post soon about this. Let them know if you have any questions. For this pr could you please re-submit with the new commit message.

Also could you please not commit the macros and tests. I am currently working on a content targeting test with staging and I believe I have come up with way to make the publish staging macros more useful. I believe this change will include everything you are trying to do, but in a slightly different way. I'll include you in the pr and you can comment if you have suggestions or disagree with the changes.

summary:
1. please recommit with only the path changes
2. please change the commit message to LRQA-14152 - paths

Please let me know if you have any questions. Thank you

**Comment by kmaria** [comment]
Hi @evannagayama,

pr is updated as you suggested.
Can hardly wait to see your  macro solution.

Cheers,
Maria

@matethurzo - fyi

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/30

**Pull request closed without merging**
