### PR TITLE
master-qa-22101

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-22101

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama 

Looking at these errors, they're due to the new changes in the PR tester server stacking on different Portal Instances, and neither of those tests are affected by my changes.

**Comment by brianwulbern** [comment]
My changes basically extract Site searching out of Page#add, and uses an extracted Site#inputSearchCP wherever tests might flakily fail when trying to add a page to a Child Site.

This will cut down on the flakiness the Site table generates, because Poshi won't have to find a Site's dropdown ellipsis _twice_ if the Site is already on the list - and tests will search for Child Sites that aren't listed on the main page.

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
ci:retest

**Pull request closed without merging**
