### PR TITLE
master-qa-15612

### PR DESCRIPTION
**Pull request by koor4356**
https://issues.liferay.com/browse/LRQA-15612

### CODE REVIEW

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed back to Koor.
1. Delete the defaultOption you added in Portlet.macro and use portletNameBorderless instead
2. Change everything you named "default" to "embedded" referring to the navigation breadcrumb
3. Try to combine the 4 similar View Breadcrumb macros

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:retest

**Comment by koor4356** [comment]
ci:tretest

**Comment by koor4356** [comment]
ci:retest

**Comment by evannagayama** [comment]
SF for KGai.
1. Combined the instances of the Breadcrumb#viewPG macro that were being called unecessarily 2 times
2. Removed and unnecessary macro

**Comment by evannagayama** [comment]
Pushed to BChiu.
https://github.com/brianchiu/liferay-portal/pull/360

**Pull request closed without merging**
