### PR TITLE
master-lps-63052 (rebased)

### PR DESCRIPTION
**Pull request by juliocamarero**

### CODE REVIEW

**Comment by evannagayama** [comment]
re: https://github.com/evannagayama/liferay-portal/pull/539

**Comment by evannagayama** [comment]
Hey Julio you had said:

> Hey Evan, 
> we just added the success message in this pull: #530 
> The back button is only shown when you navigate inside the administration. For example, if you go to Web Content, you don't see a back button. However, once you navigate inside the app you see it. The same happens here, when you click on add there is no back button.
>Thanks!

Does this mean after creating a page there should be a success message? Because just looking over the test results in the last pr, they failed because there wasn't a success message (https://github.com/evannagayama/liferay-portal/pull/539). I'll build this after it runs and double check, but just wanted to see if you knew the answer already. Thanks

**Comment by juliocamarero** [comment]
mmm... that's weird...  last time I tested it we had a succes message in the page the user is redirected too...

If you don't see it just let us know and we will test again.

thank you!

**Comment by evannagayama** [comment]
@juliocamarero I just built it and there is a success message, but the ui is a bit off

**Comment by juliocamarero** [comment]
mmm... you mean the message not being translated or something else?

**Comment by evannagayama** [comment]
@juliocamarero this is the old and normal success message. The one in this pr just has the dashes and doesn't look clean.

selection_030

**Comment by juliocamarero** [comment]
Hey @evannagayama 

I have just updated the pull adding the localized message. 

I still don't see what you mean by it doesn't  look clean :joy: 

If we can pass the pull, I can fix that later :+1: 

thank you!!

**Comment by evannagayama** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed here: https://github.com/evannagayama/liferay-portal/pull/543

**Pull request closed without merging**
