### PR TITLE
LPS-62065 Clean up js

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by evannagayama** [comment]
@koor43 can look into this and make test fixes? Thanks!

**Comment by ealonso** [comment]
@evannagayama, I think you were referring to @koor4356, :smile:

**Comment by koor4356** [comment]
@ealonso @evannagayama I will look into these poshi failures.

**Comment by evannagayama** [comment]
lol thanks @ealonso

**Comment by koor4356** [comment]
@ealonso I've made test fixes here https://github.com/evannagayama/liferay-portal/pull/462 and it has been to push @evannagayama.

I've notice that product menu panel remains open when other panels are open. Can you look into this please?

**Comment by ealonso** [comment]
Hey @koor4356, @evannagayama,

We know this issue, but is intented for now. We need this code on master to talk with Patrick and Marcos to fix it on Lexicon.

Thanks you very much for the test fixes.

**Pull request closed without merging**
