### PR TITLE
master-qa-21575

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-21575

### CODE REVIEW

**Comment by brianwulbern** [comment]
@evannagayama 
By some miracle, this rebased locally without issue.  We might want to run a User Branch on this one, if there are failing P5s.

**Comment by brianwulbern** [comment]
@evannagayama 

don't retest this yet

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
@evannagayama 
Looks like the WorkflowadminCPBlogs#ApproveBlogsEntryCP test was aborted.  That test already has undergone Navigator streamlining; the Page#openURL doesn't apply to it.

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35153

**Pull request closed without merging**
