### PR TITLE
master-qa-22765

### PR DESCRIPTION
**Pull request by brianwulbern**
https://issues.liferay.com/browse/LRQA-22765

### CODE REVIEW

**Comment by brianwulbern** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
waiting on user branch tester
https://test-3-3.liferay.com/job/test-portal-branch-user(master)/

**Comment by brianwulbern** [comment]
@evannagayama 
Just rebased it.  I guess this time tomorrow, we'll have to backport to this pull

**Comment by brianwulbern** [comment]
ci:retest

**Comment by evannagayama** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/38405

**Pull request closed without merging**
