### PR TITLE
LPS-63052 redirect users to the page they just created

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Evan,

this pull changes where the user is redirected after creating a page. Now, after a page is created, the user is taken to that page.

I still need to figure out what to do with the success message... probably we won't show it at all, but I need to check with the UX guys... 

thank you!

### CODE REVIEW

**Comment by evannagayama** [comment]
@juliocamarero do you know when the final decision will be made about the success message? If it won't be too long, maybe we can wait and push it all together? 

For now I'll make sure nothing else is breaking and make temporary fix, then tomorrow I can push it in or wait. Thanks

**Comment by evannagayama** [comment]
@juliocamarero I think there is a bug on this pr. When adding a child page, the back button is missing. I just noticed and wasn't able to check the normal page, but it might be missing there too. Could you check this? Thanks

**Comment by juliocamarero** [comment]
Hey Evan, 

we just added the success message in this pull: https://github.com/evannagayama/liferay-portal/pull/530

The back button is only shown when you navigate inside the administration. For example, if you go to Web Content, you don't see a back button. However, once you navigate inside the app you see it. The same happens here, when you click on add there is no back button.

Thanks!

**Comment by evannagayama** [comment]
Ok I see the new functionality. I'll work on this today. Thanks Julio!

**Comment by evannagayama** [comment]
pushed here: https://github.com/evannagayama/liferay-portal/pull/530

**Pull request closed without merging**
