### PR TITLE
LRQA-19777- Testscases from SiteMap testplan with a few public pages and child pages

### PR DESCRIPTION
**Pull request by asungutierrez**

### CODE REVIEW

**Comment by evannagayama** [comment]
@asungutierrez sorry I didn't get a chance to look at this today and it didn't finish running. Could you please rebase it and resend and I'll try to look at it tomorrow? Thank you!

**Comment by asungutierrez** [comment]
ci:retest

**Comment by juliocamarero** [comment]
ci:retest

**Comment by evannagayama** [comment]
@asungutierrez how is it going with writing? Have you run into any more issues that you are stuck on?

**Comment by asungutierrez** [comment]
I've sent you new changes in this test case. 
https://github.com/evannagayama/liferay-portal/pull/589

You can see them in this link.

**Comment by evannagayama** [comment]
Closing as pushed again here: https://github.com/evannagayama/liferay-portal/pull/589

**Pull request closed without merging**
